version: '3'
services:
  sls:
    build: ./Serverless
    depends_on:
    - db
    environment:
    - DB=mongodb://db:27017/resources

  api:
    build: ./dockerApp
    depends_on:
    - db
    environment:
    - DB=mongodb://db:27017/resources
    - PORT=8080
    ports:
    - "2121:8080"

  db:
    image: mongo
    ports:
    - "27027:27017"