version: '3'
services:
  sls:
    build: ./Serverless
    environment:
    - DB=mongodb://db:27017/db
    - PORT=3050
    ports:
    - "3000:3000"
    networks:
    - killemall

  api:
    build: ./dockerApp
    depends_on:
    - db
    environment:
    - DB=mongodb://db:27017/resources
    - PORT=8080
    ports:
    - "2121:8080"
    networks:
    - killemall

  db:
    image: mongo
    ports:
    - "27027:27017"
    networks:
    - killemall

networks:
  killemall: