version: '3'
services:
  sls:
    build: ./Serverless
    depends_on:
    - db
    environment:
    #      -
    ports:
    - ":"

  api:
    build: ./dockerApp
    depends_on:
    - db
    environment:
    #    -
    ports:
    - ":"

  db:
    image: mongo
    ports:
    - "27027:27017"