service: listGenerator

custom:
  serverless-offline:
    host: 0.0.0.0

provider:
  name: aws
  runtime: nodejs8.10

functions:
  updateVillain:
    handler: ./Handlers/villains.updateV
    events:
    - http: POST /updateV

  resetVillain:
    handler: ./Handlers/villains.resetV
    events:
    - http: POST /resetV

  getMechants:
    handler: ./Handlers/villains.getV
    events:
    - http: GET /getV

  getPoney:
    handler: ./Handlers/poney.updateP
    events:
    - http: POST /updateP

  updatePoney:
    handler: ./Handlers/poney.getP
    events:
    - http: GET /getP

  updateHero:
    handler: ./Handlers/hero.updateH
    events:
    - http: POST /updateH

  getHero:
    handler: ./Handlers/hero.getH
    events:
    - http: GET /getH


plugins:
- serverless-offline