service: listGenerator

provider:
  name: aws
  runtime: nodejs8.10

functions:
  updateVillain:
    handler: ./Handlers/villains.updateV
    events:
    - http: POST /updateV

  getMechants:
    handler: ./Handlers/villains.getV
    events:
    - http: GET /getV

  getPoney:
    handler: ./Handlers/poney.updateP
    events:
    - http: POST /updateP

  updatePoney:
    handler: ./Handlers/poney.getP
    events:
    - http: GET /getP

  getHero:
    handler: ./Handlers/hero.updateH
    events:
    - http: POST /updateP

  updateHero:
    handler: ./Handlers/hero.getH
    events:
    - http: GET /getP


plugins:
- serverless-offline